### ISSUE TITLE
Apply multiple settings at once

### ISSUE THREAD

**Issue by Ian2020** [jistr/ansible-gsetting#14]
I would like to apply multiple settings at once. I have up to 60 settings for some users and it can take over **40 seconds** to apply via a loop over this module, a significant chunk of my ansible run. The code in the suggested PR brings this down to around **6 seconds** as ansible only runs the module once, and we avoid repeated calls to fetch the dbus session.

I would suggest this requires a new and breaking argument spec such that a task would look like this:

    - name: apply my GNOME settings
      gsetting:
        user: jistr
        settings:
          org.gnome.shell.remember-mount-password: false
          org.gnome.desktop.wm.keybindings.panel-main-menu: "@as []"
          org.gnome.nautilus.preferences.default-folder-viewer: "'list-view'"

The module will return a status of changed when **any one** of the given settings has been updated.

Here's a real world example play where we call the module and then debug the results:

```yaml
- name: Apply GNOME settings
  become: yes
  gsetting:
    settings:
      # Press power button, should no nothing
      org.gnome.settings-daemon.plugins.power.power-button-action:  "'nothing'"
      # Setup Night Light
      org.gnome.settings-daemon.plugins.color.night-light-schedule-automatic: "false"
      org.gnome.settings-daemon.plugins.color.night-light-schedule-to: "7.0"
      # Extension: Freon
      org.gnome.shell.extensions.freon.show-decimal-value: "false"
      org.gnome.shell.extensions.freon.position-in-panel: "'left'"
  register: gsettings
- debug: var=gsettings
```
And the corresponding ansible output when two settings are changed and the rest are not:

```text
TASK [Apply GNOME settings] ******************************************************************************
changed: [localhost]

TASK [debug] **********************************************************************************************************
ok: [localhost] => {
    "gsettings": {
        "changed": true,
        "changed_settings": [
            {
                "key": "org.gnome.shell.extensions.freon.show-decimal-value",
                "new_value": "false",
                "value": "true"
            },
            {
                "key": "org.gnome.shell.extensions.freon.position-in-panel",
                "new_value": "'left'",
                "value": "'right'"
            }
        ],
        "failed": false,
        "unchanged_settings": [
            {
                "key": "org.gnome.settings-daemon.plugins.power.power-button-action",
                "value": "'nothing'"
            },
            {
                "key": "org.gnome.settings-daemon.plugins.color.night-light-schedule-automatic",
                "value": "false"
            },
            {
                "key": "org.gnome.settings-daemon.plugins.color.night-light-schedule-to",
                "value": "7.0"
            }
        ]
    }
}

```

Let me know what you think, it's only a suggestion and I'll understand if it's not the right direction for this module. There aren't many ansible modules that apply multiple changes at once that I've found.
