### ISSUE TITLE
Support specifying both schema and path

### ISSUE THREAD

**Issue by radomirbosak** [jistr/ansible-gsetting#4]
I'd like to issue basically this command
```console
$ gsettings get org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name
```

But I have to fake this with the setting
```yaml
- name: new terminal shortcut
  gsetting:
    user: me
    key: "org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/.name"
    value: "New terminal"
```

The path must be specified in the case, since the schema for custom keyboard shortcuts is relocatable:
```console
$ gsettings get org.gnome.settings-daemon.plugins.media-keys.custom-keybinding name
Schema “org.gnome.settings-daemon.plugins.media-keys.custom-keybinding” is relocatable (path must be specified)
```
